### ISSUE TITLE
`require': cannot load such file -- win32ole (LoadError)

### ISSUE THREAD

**Issue by shivareddy547** [tomiacannondale/wrap_excel#1]
After installing gem if i try to run the code it s giving error like  
require': cannot load such file -- win32ole (LoadError)
What i can do for this.
I am using Ubuntu 14.0,ruby 1.9.3.

Please help me.

Thanks in Advance.

Thanks
Shiva.A

**Comment by tomiacannondale** [comment]
Sorry for late!
WrapExcel support only windows. Because this gem use [win32ole](http://ruby-doc.org/stdlib-1.9.3/libdoc/win32ole/rdoc/WIN32OLE.html) .
If you modify excel files on Ubuntu, You can use [spreadsheet](https://github.com/zdavatz/spreadsheet) .

I created [rusk](https://github.com/tomiacannondale/rusk) which can read and write Open Document Spreadsheet Format(ods) files.

Thanks
Tomi
